In [1]:
import torch
import torch.nn as nn
from torchvision.datasets import ImageFolder
from collections import Counter

In [2]:
from torchvision.datasets import ImageFolder

train_dataset = ImageFolder(
    r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge"
)

In [3]:
train_dataset = ImageFolder(
    r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge")
print("Classes:",train_dataset.classes)
print("Dataset size:",len(train_dataset))

Classes: ['ambulance', 'autobus', 'kamyun', 'kamyunet', 'minibus', 'savari', 'taxi', 'vanet']
Dataset size: 1932

In [4]:
count = Counter(train_dataset.targets)
print(count)

Counter({2: 250, 5: 250, 6: 250, 7: 250, 1: 245, 3: 238, 4: 230, 0: 219})

In [5]:
print("Class    \t\t  Count")
for class_id , class_name in enumerate(train_dataset.classes):
    print(f"{class_name}    \t\t  {count[class_id]}")

Class    		  Count
ambulance    		  219
autobus    		  245
kamyun    		  250
kamyunet    		  238
minibus    		  230
savari    		  250
taxi    		  250
vanet    		  250

In [6]:
from pathlib import Path
train_dir = Path( 
    r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge")

In [7]:
print(train_dir.exists())

True

In [8]:
print(train_dir.is_dir())

True

In [9]:
print(list(train_dir.iterdir()))

[WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/ambulance'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/autobus'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/kamyun'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/kamyunet'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/minibus'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/savari'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/taxi'), WindowsPath('C:/Users/ASUS/Desktop/مکتب شریف/مکتب 145/پروژه دوم/data/train - merge/vanet')]

In [10]:
for item in train_dir.iterdir():
    print(item)

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\autobus
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\kamyun
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\kamyunet
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\minibus
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\savari
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\taxi
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\vanet

In [11]:
file = train_dir.rglob("*")
print(len(list(train_dir.rglob("*"))))

1940

In [12]:
for item in train_dir.rglob("*"):
    print(item)

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\autobus
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\kamyun
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\kamyunet
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\minibus
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\savari
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\taxi
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\vanet
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\195939523.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\198727855.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199031396.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199587392.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199659807.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199984667.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\200011359.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\200805520.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\201107960.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\203158523.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\203539792.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\203829862.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\204215951.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\204227881.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\205326290.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\206000918.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\206174864.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\206808986.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\208466531.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\208738861.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\209441415.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\209741797.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\209817390.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\209819480.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\211623028.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\211676031.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\211786744.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\211940909.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\211966435.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\211996658.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\212007692.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\212181645.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\212409258.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\212750815.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\212822076.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213029149.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213064777.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213283576.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213342200.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213357768.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213490536.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213801906.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\213805984.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214162077.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214354132.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214358069.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214425638.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214485304.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214491219.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214493399.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214587510.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214641358.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214715793.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214725360.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214784967.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\214803565.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215086043.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215101954.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215162191.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215455492.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215691126.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215731258.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215767078.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215775115.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215799618.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215890423.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215895473.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215922180.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\215998859.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216005219.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216013688.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216018033.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216019173.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216026223.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216029056.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216035809.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216048174.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216059668.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216066730.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216077999.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216092441.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216105563.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216113788.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216118298.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216128960.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216143298.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216146573.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216152703.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216157856.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216216403.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216224583.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216232960.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216242769.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216256793.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216287989.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216379768.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216400367.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216447391.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216449202.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216527609.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216533019.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216561672.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216612929.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216657686.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216657889.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216673206.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216753875.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216765169.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216773853.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216777388.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216780041.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216816417.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216820535.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216834352.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216840747.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216843475.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216864213.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216903655.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216915388.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216951685.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216952196.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216959847.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216974433.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\216983143.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217037450.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217043669.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217088412.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217119220.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217150612.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217155355.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217206154.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217208536.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217209937.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217226406.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217250077.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217302360.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217323781.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217324168.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217381140.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217402380.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217402945.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217447963.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217477279.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217477434.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217480566.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217496158.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217497126.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217499646.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217504681.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217506368.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217526919.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217541742.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217551252.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217570069.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217579095.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217584509.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217652202.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217697159.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217727567.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217785400.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217814338.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217825810.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217888265.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217910074.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217940480.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\217986910.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218036224.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218078334.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218119796.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218153518.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218191394.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218193739.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218204858.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218244029.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218249834.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218254848.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218266352.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218289823.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218289961.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218308494.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218315928.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218316367.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218332655.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218339551.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218343183.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218353709.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218384303.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218420550.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218506566.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218591595.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218621416.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218659907.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218673872.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218676611.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218701191.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218702745.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218705819.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218729538.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218737689.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218808822.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218811675.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218816506.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218819549.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218819949.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218820152.jpg
C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\218852971.jpg

In [13]:
files = [file for file in train_dir.rglob("*") if file.is_file()]
print(len(files))

1932

بررسی پسوند فایل ها

In [14]:
count_jpg , count_jpeg , count_png = 0 , 0, 0
for item in train_dir.rglob("*"):
    if item.is_file():

        if item.suffix == ".jpg":
            count_jpg += 1
        elif item.suffix == ".png":
            count_png += 1
        elif item.suffix == ".jpeg":
            count_jpeg += 1
        else:
            print("Unknown extension:", item.suffix) # پسوند ناشناخته (پسوند فایل را چاپ کن)
print("count jpg  :", count_jpg)
print("count jpeg  :", count_jpeg)
print("count png  :", count_png)

count jpg  : 1932
count jpeg  : 0
count png  : 0

بررسی خراب یا سالم بودن عکس ها

In [15]:
from PIL import Image
import os 

for item in train_dir.rglob("*"):
    if item.is_file():
        try:
            Image.open(item)
        except UnidentifiedImageError:  # این خطا مخصوص زمانی است که PIL نمی تواند فایل را به عنوان یک تصویر معتبر شناسایی کند
            print("The image file is corrupted.",item)

 بررسی ابعاد تصویر

In [16]:
for item in train_dir.rglob("*"):
    if item.is_file():
        img = Image.open(item)
        print(img.size)

(307, 366)
(328, 365)
(253, 333)
(290, 326)
(286, 328)
(269, 397)
(272, 372)
(263, 341)
(263, 401)
(270, 355)
(269, 336)
(305, 353)
(290, 360)
(289, 339)
(248, 313)
(408, 495)
(268, 289)
(279, 366)
(237, 317)
(284, 339)
(222, 275)
(171, 216)
(162, 216)
(195, 264)
(162, 216)
(168, 216)
(198, 264)
(207, 259)
(162, 216)
(210, 265)
(207, 276)
(156, 204)
(180, 228)
(281, 326)
(207, 276)
(186, 252)
(189, 252)
(156, 204)
(189, 252)
(210, 270)
(156, 204)
(162, 216)
(210, 276)
(162, 204)
(189, 252)
(462, 956)
(207, 273)
(198, 264)
(171, 228)
(165, 216)
(180, 240)
(177, 240)
(198, 264)
(186, 252)
(177, 228)
(198, 247)
(162, 216)
(156, 204)
(186, 235)
(186, 252)
(186, 240)
(162, 216)
(186, 252)
(171, 228)
(180, 240)
(189, 252)
(195, 264)
(156, 216)
(189, 240)
(165, 216)
(270, 361)
(186, 237)
(177, 240)
(198, 250)
(207, 254)
(189, 252)
(165, 216)
(189, 252)
(162, 216)
(207, 276)
(141, 180)
(150, 192)
(198, 252)
(171, 216)
(198, 247)
(156, 204)
(189, 230)
(380, 787)
(210, 276)
(189, 240)
(180, 228)
(171, 228)
(195, 252)
(162, 216)
(425, 852)
(177, 228)
(156, 204)
(145, 216)
(162, 216)
(207, 274)
(189, 252)
(256, 363)
(162, 216)
(198, 264)
(198, 264)
(186, 252)
(198, 264)
(186, 252)
(198, 252)
(198, 264)
(180, 228)
(135, 180)
(171, 228)
(198, 264)
(150, 192)
(207, 276)
(198, 264)
(189, 240)
(135, 180)
(198, 252)
(168, 228)
(198, 252)
(370, 553)
(156, 204)
(117, 216)
(168, 228)
(171, 228)
(207, 276)
(120, 168)
(129, 180)
(207, 254)
(186, 252)
(189, 252)
(156, 204)
(156, 204)
(198, 239)
(162, 216)
(198, 276)
(189, 252)
(162, 216)
(180, 240)
(189, 240)
(198, 247)
(180, 228)
(186, 240)
(180, 240)
(180, 240)
(165, 216)
(171, 216)
(186, 252)
(210, 276)
(177, 228)
(171, 228)
(177, 220)
(123, 168)
(162, 216)
(198, 264)
(165, 216)
(177, 240)
(186, 252)
(150, 189)
(186, 252)
(129, 180)
(198, 252)
(162, 216)
(171, 228)
(171, 228)
(198, 264)
(189, 252)
(198, 276)
(180, 240)
(201, 263)
(162, 216)
(271, 333)
(150, 189)
(171, 228)
(177, 228)
(198, 264)
(198, 264)
(156, 204)
(207, 276)
(198, 264)
(171, 202)
(168, 228)
(390, 870)
(198, 252)
(189, 236)
(207, 276)
(189, 252)
(162, 216)
(171, 228)
(258, 356)
(180, 240)
(249, 382)
(171, 216)
(165, 216)
(171, 228)
(168, 228)
(177, 240)
(189, 240)
(207, 271)
(150, 192)
(207, 262)
(186, 252)
(207, 276)
(207, 264)
(177, 230)
(189, 252)
(268, 300)
(150, 192)
(321, 812)
(177, 240)
(207, 276)
(150, 192)
(162, 204)
(201, 264)
(189, 252)
(177, 240)
(210, 276)
(381, 440)
(361, 324)
(395, 440)
(374, 254)
(367, 349)
(434, 439)
(381, 387)
(337, 367)
(235, 260)
(378, 440)
(401, 381)
(266, 274)
(385, 440)
(415, 398)
(379, 341)
(380, 404)
(234, 225)
(666, 844)
(379, 352)
(376, 334)
(358, 426)
(441, 440)
(303, 293)
(326, 410)
(386, 418)
(386, 440)
(293, 418)
(288, 332)
(327, 330)
(241, 280)
(334, 450)
(323, 440)
(545, 590)
(376, 450)
(356, 450)
(318, 393)
(331, 450)
(361, 450)
(341, 450)
(371, 437)
(328, 507)
(189, 248)
(189, 240)
(359, 448)
(186, 237)
(369, 432)
(321, 448)
(353, 450)
(318, 450)
(349, 450)
(344, 448)
(325, 450)
(321, 436)
(186, 252)
(180, 228)
(198, 264)
(207, 276)
(150, 189)
(296, 359)
(395, 448)
(422, 448)
(370, 448)
(379, 448)
(198, 264)
(411, 448)
(210, 270)
(345, 447)
(156, 204)
(186, 240)
(384, 443)
(156, 204)
(331, 448)
(320, 423)
(343, 448)
(189, 252)
(317, 406)
(207, 268)
(342, 448)
(198, 240)
(390, 448)
(344, 444)
(432, 448)
(189, 252)
(433, 448)
(198, 264)
(331, 448)
(210, 270)
(412, 448)
(403, 448)
(344, 448)
(341, 448)
(429, 448)
(198, 260)
(222, 273)
(331, 444)
(365, 448)
(349, 448)
(366, 448)
(366, 448)
(332, 445)
(388, 442)
(352, 448)
(340, 448)
(342, 448)
(406, 448)
(201, 264)
(198, 276)
(356, 448)
(198, 252)
(189, 252)
(419, 448)
(329, 442)
(339, 448)
(295, 366)
(392, 448)
(431, 448)
(354, 448)
(343, 448)
(198, 264)
(198, 252)
(365, 448)
(198, 254)
(180, 228)
(144, 192)
(382, 448)
(354, 448)
(333, 448)
(336, 448)
(350, 448)
(189, 240)
(186, 236)
(351, 448)
(389, 448)
(198, 252)
(198, 252)
(315, 448)
(357, 448)
(186, 252)
(322, 443)
(207, 274)
(311, 379)
(367, 448)
(390, 448)
(210, 276)
(198, 252)
(328, 448)
(358, 448)
(339, 448)
(306, 448)
(207, 276)
(334, 448)
(306, 406)
(347, 448)
(347, 448)
(369, 448)
(326, 448)
(411, 448)
(338, 448)
(335, 448)
(352, 448)
(207, 276)
(373, 448)
(359, 448)
(359, 448)
(347, 448)
(392, 448)
(348, 448)
(367, 448)
(207, 243)
(198, 264)
(393, 448)
(306, 414)
(189, 240)
(358, 448)
(198, 254)
(402, 448)
(323, 448)
(332, 448)
(337, 447)
(348, 448)
(357, 448)
(362, 448)
(388, 440)
(198, 264)
(201, 264)
(320, 448)
(347, 448)
(210, 276)
(319, 421)
(349, 448)
(345, 445)
(368, 448)
(427, 448)
(373, 448)
(334, 435)
(332, 440)
(364, 448)
(180, 240)
(388, 448)
(409, 415)
(388, 448)
(341, 448)
(322, 444)
(373, 410)
(332, 448)
(342, 448)
(325, 439)
(354, 448)
(299, 411)
(168, 228)
(326, 448)
(185, 252)
(207, 276)
(306, 404)
(352, 448)
(180, 240)
(207, 276)
(195, 252)
(372, 448)
(348, 448)
(324, 448)
(375, 448)
(189, 252)
(392, 448)
(349, 448)
(352, 448)
(163, 264)
(314, 414)
(376, 448)
(186, 240)
(207, 276)
(339, 448)
(356, 448)
(329, 372)
(337, 448)
(171, 216)
(351, 448)
(198, 264)
(340, 448)
(385, 448)
(207, 260)
(292, 364)
(180, 228)
(284, 445)
(310, 432)
(413, 426)
(352, 440)
(420, 421)
(392, 440)
(369, 329)
(405, 392)
(350, 408)
(402, 373)
(325, 384)
(364, 440)
(306, 352)
(354, 450)
(418, 440)
(306, 372)
(310, 351)
(329, 355)
(255, 249)
(348, 440)
(319, 413)
(256, 312)
(265, 301)
(337, 435)
(342, 379)
(325, 376)
(319, 342)
(315, 428)
(391, 336)
(322, 422)
(293, 306)
(302, 278)
(381, 450)
(311, 433)
(361, 482)
(278, 267)
(379, 433)
(308, 419)
(195, 246)
(366, 419)
(352, 412)
(382, 416)
(150, 192)
(351, 340)
(195, 264)
(304, 417)
(198, 252)
(186, 252)
(219, 276)
(198, 252)
(356, 448)
(314, 419)
(189, 223)
(446, 448)
(180, 228)
(210, 261)
(342, 448)
(189, 252)
(326, 444)
(320, 448)
(198, 264)
(332, 425)
(317, 333)
(210, 276)
(249, 216)
(128, 192)
(198, 252)
(314, 413)
(278, 358)
(305, 403)
(330, 418)
(345, 355)
(338, 346)
(210, 257)
(302, 376)
(180, 228)
(198, 252)
(349, 448)
(156, 216)
(198, 264)
(341, 429)
(350, 448)
(270, 253)
(315, 353)
(198, 264)
(353, 390)
(210, 261)
(340, 448)
(312, 417)
(186, 252)
(162, 204)
(331, 355)
(323, 433)
(198, 264)
(177, 240)
(171, 228)
(362, 448)
(306, 425)
(186, 252)
(198, 252)
(198, 264)
(198, 252)
(378, 448)
(331, 448)
(336, 411)
(195, 264)
(298, 283)
(181, 260)
(298, 416)
(171, 228)
(186, 252)
(362, 448)
(345, 375)
(210, 276)
(319, 332)
(382, 448)
(195, 252)
(186, 252)
(298, 362)
(335, 417)
(328, 417)
(302, 355)
(327, 396)
(189, 252)
(366, 406)
(335, 404)
(345, 407)
(285, 341)
(342, 410)
(312, 448)
(351, 412)
(285, 320)
(195, 264)
(207, 264)
(357, 448)
(290, 319)
(373, 438)
(361, 442)
(325, 446)
(432, 417)
(324, 433)
(313, 304)
(304, 318)
(384, 416)
(340, 408)
(373, 404)
(311, 369)
(198, 237)
(186, 240)
(319, 346)
(336, 387)
(340, 448)
(198, 252)
(358, 359)
(321, 276)
(294, 405)
(198, 252)
(304, 420)
(318, 409)
(357, 407)
(137, 252)
(153, 252)
(195, 264)
(337, 405)
(350, 410)
(318, 400)
(332, 341)
(346, 448)
(330, 357)
(317, 448)
(332, 388)
(331, 448)
(292, 347)
(303, 376)
(299, 368)
(374, 448)
(311, 433)
(297, 412)
(313, 369)
(338, 411)
(320, 351)
(336, 427)
(195, 252)
(334, 448)
(291, 418)
(365, 448)
(195, 252)
(340, 448)
(195, 264)
(337, 448)
(362, 383)
(323, 442)
(310, 395)
(309, 324)
(286, 414)
(382, 392)
(331, 430)
(357, 408)
(349, 448)
(198, 264)
(403, 440)
(372, 448)
(207, 232)
(327, 448)
(198, 264)
(340, 448)
(347, 448)
(348, 363)
(356, 413)
(180, 228)
(163, 232)
(319, 416)
(313, 347)
(307, 372)
(333, 446)
(318, 401)
(347, 448)
(315, 406)
(329, 448)
(316, 407)
(303, 365)
(347, 448)
(311, 335)
(298, 444)
(328, 426)
(316, 342)
(336, 423)
(376, 448)
(317, 429)
(347, 448)
(345, 448)
(341, 409)
(198, 264)
(266, 305)
(346, 448)
(186, 252)
(297, 369)
(349, 375)
(180, 240)
(171, 216)
(295, 418)
(195, 252)
(329, 386)
(336, 415)
(356, 349)
(310, 352)
(256, 382)
(210, 272)
(250, 361)
(247, 340)
(265, 285)
(250, 331)
(383, 435)
(367, 384)
(350, 364)
(317, 370)
(347, 326)
(389, 393)
(314, 388)
(304, 340)
(306, 222)
(287, 290)
(303, 302)
(308, 319)
(371, 354)
(255, 252)
(287, 342)
(346, 302)
(249, 289)
(268, 396)
(298, 267)
(267, 308)
(222, 201)
(326, 310)
(289, 367)
(450, 364)
(272, 342)
(253, 322)
(273, 419)
(296, 315)
(280, 290)
(337, 275)
(310, 378)
(312, 405)
(278, 346)
(251, 386)
(270, 415)
(284, 358)
(274, 333)
(180, 240)
(177, 240)
(164, 240)
(177, 240)
(189, 240)
(198, 244)
(281, 393)
(241, 297)
(210, 276)
(207, 243)
(290, 344)
(277, 392)
(303, 399)
(270, 386)
(277, 368)
(291, 358)
(198, 252)
(276, 397)
(286, 387)
(299, 448)
(189, 240)
(180, 229)
(315, 448)
(269, 392)
(299, 446)
(274, 394)
(548, 754)
(271, 271)
(308, 350)
(198, 264)
(315, 448)
(162, 216)
(186, 252)
(302, 311)
(156, 204)
(198, 264)
(256, 239)
(276, 380)
(189, 252)
(186, 240)
(314, 380)
(195, 264)
(171, 228)
(293, 301)
(328, 395)
(186, 252)
(313, 401)
(198, 276)
(271, 376)
(358, 368)
(195, 252)
(171, 228)
(315, 377)
(207, 264)
(286, 240)
(198, 264)
(303, 377)
(331, 317)
(291, 329)
(313, 399)
(198, 264)
(275, 354)
(278, 296)
(198, 264)
(189, 252)
(310, 448)
(272, 415)
(258, 366)
(291, 307)
(195, 264)
(270, 290)
(207, 276)
(316, 408)
(278, 381)
(338, 448)
(162, 216)
(186, 240)
(189, 252)
(186, 252)
(276, 390)
(257, 333)
(210, 264)
(286, 389)
(268, 323)
(309, 416)
(210, 254)
(283, 357)
(294, 370)
(275, 327)
(275, 391)
(238, 287)
(301, 410)
(207, 268)
(285, 381)
(301, 366)
(306, 346)
(275, 369)
(198, 264)
(295, 425)
(207, 261)
(307, 322)
(189, 252)
(313, 446)
(276, 321)
(320, 241)
(210, 243)
(186, 240)
(312, 342)
(291, 386)
(189, 252)
(322, 416)
(264, 303)
(275, 384)
(306, 409)
(198, 264)
(332, 334)
(282, 387)
(287, 430)
(289, 327)
(353, 448)
(310, 405)
(325, 420)
(279, 316)
(273, 311)
(210, 276)
(150, 192)
(292, 373)
(180, 223)
(281, 388)
(289, 307)
(284, 385)
(281, 352)
(330, 368)
(345, 448)
(195, 255)
(171, 228)
(282, 375)
(261, 345)
(294, 411)
(305, 420)
(254, 232)
(293, 345)
(268, 323)
(198, 240)
(313, 398)
(291, 311)
(285, 367)
(271, 406)
(265, 318)
(301, 423)
(198, 210)
(329, 448)
(273, 287)
(277, 387)
(282, 347)
(292, 291)
(189, 235)
(198, 251)
(180, 252)
(171, 228)
(207, 276)
(281, 320)
(198, 264)
(135, 180)
(250, 281)
(275, 308)
(283, 370)
(283, 304)
(278, 357)
(285, 347)
(180, 240)
(323, 444)
(210, 276)
(354, 424)
(267, 241)
(267, 284)
(278, 370)
(320, 318)
(283, 254)
(255, 323)
(293, 369)
(189, 240)
(277, 360)
(189, 235)
(144, 192)
(189, 252)
(290, 293)
(186, 232)
(269, 330)
(168, 232)
(293, 426)
(298, 448)
(294, 397)
(207, 276)
(208, 332)
(183, 296)
(205, 280)
(211, 415)
(177, 310)
(170, 310)
(187, 320)
(325, 367)
(289, 301)
(331, 360)
(369, 364)
(312, 388)
(311, 408)
(281, 392)
(305, 400)
(290, 386)
(359, 399)
(294, 324)
(297, 326)
(250, 339)
(272, 376)
(294, 338)
(313, 333)
(337, 361)
(354, 333)
(273, 356)
(299, 360)
(285, 353)
(322, 367)
(321, 369)
(280, 381)
(287, 366)
(273, 368)
(303, 409)
(256, 373)
(251, 323)
(312, 339)
(293, 376)
(294, 399)
(356, 344)
(271, 373)
(317, 319)
(283, 309)
(378, 450)
(305, 450)
(364, 450)
(375, 450)
(354, 450)
(351, 450)
(366, 450)
(367, 442)
(397, 450)
(341, 383)
(378, 450)
(376, 450)
(394, 450)
(345, 440)
(354, 450)
(393, 450)
(389, 450)
(361, 447)
(352, 450)
(380, 450)
(317, 450)
(343, 450)
(316, 450)
(280, 334)
(360, 442)
(387, 450)
(383, 450)
(382, 450)
(362, 439)
(282, 406)
(288, 391)
(300, 415)
(177, 240)
(287, 395)
(198, 264)
(198, 240)
(134, 264)
(195, 243)
(198, 210)
(189, 240)
(298, 373)
(186, 252)
(268, 353)
(306, 381)
(304, 366)
(210, 269)
(280, 365)
(310, 390)
(210, 276)
(296, 370)
(207, 273)
(207, 288)
(138, 180)
(198, 252)
(207, 264)
(195, 264)
(265, 371)
(275, 360)
(287, 352)
(287, 349)
(198, 264)
(276, 354)
(210, 268)
(287, 354)
(322, 401)
(290, 364)
(198, 264)
(300, 356)
(288, 344)
(275, 368)
(207, 210)
(281, 373)
(186, 252)
(198, 252)
(277, 359)
(282, 439)
(287, 440)
(327, 365)
(299, 453)
(288, 353)
(268, 359)
(283, 347)
(291, 354)
(207, 261)
(298, 358)
(274, 354)
(207, 257)
(289, 353)
(287, 351)
(267, 358)
(299, 393)
(317, 325)
(302, 343)
(294, 359)
(282, 363)
(247, 345)
(291, 352)
(288, 351)
(284, 366)
(198, 264)
(198, 252)
(292, 340)
(276, 358)
(288, 362)
(320, 395)
(290, 343)
(210, 268)
(287, 347)
(301, 354)
(271, 377)
(276, 356)
(198, 264)
(189, 240)
(286, 354)
(195, 264)
(297, 350)
(210, 264)
(189, 252)
(290, 351)
(277, 358)
(210, 264)
(293, 352)
(277, 370)
(284, 366)
(284, 355)
(287, 365)
(280, 361)
(195, 252)
(296, 348)
(210, 268)
(304, 328)
(287, 349)
(296, 354)
(297, 348)
(198, 264)
(283, 350)
(280, 359)
(198, 264)
(283, 366)
(289, 357)
(186, 252)
(295, 350)
(186, 252)
(198, 260)
(298, 348)
(284, 367)
(284, 366)
(273, 363)
(299, 349)
(264, 348)
(300, 346)
(285, 375)
(298, 351)
(198, 264)
(286, 401)
(198, 252)
(315, 365)
(295, 357)
(297, 350)
(288, 401)
(288, 361)
(293, 351)
(295, 348)
(186, 252)
(288, 354)
(290, 388)
(283, 366)
(291, 350)
(138, 180)
(307, 406)
(195, 264)
(282, 354)
(261, 350)
(207, 257)
(299, 373)
(269, 361)
(286, 363)
(285, 360)
(292, 357)
(210, 276)
(302, 397)
(288, 356)
(276, 361)
(180, 228)
(198, 252)
(295, 351)
(305, 368)
(286, 359)
(288, 367)
(189, 252)
(208, 292)
(285, 361)
(198, 300)
(186, 252)
(274, 265)
(281, 281)
(255, 250)
(216, 209)
(301, 293)
(303, 259)
(259, 252)
(319, 287)
(265, 218)
(288, 274)
(252, 296)
(269, 259)
(246, 273)
(251, 271)
(264, 210)
(278, 234)
(256, 298)
(281, 236)
(279, 290)
(236, 228)
(254, 252)
(251, 262)
(246, 326)
(263, 257)
(231, 243)
(235, 222)
(245, 227)
(245, 272)
(255, 242)
(298, 267)
(248, 251)
(222, 260)
(247, 296)
(259, 257)
(324, 279)
(278, 272)
(240, 264)
(253, 296)
(271, 264)
(292, 262)
(242, 262)
(222, 245)
(273, 271)
(264, 238)
(241, 274)
(234, 257)
(235, 261)
(262, 251)
(232, 260)
(222, 219)
(253, 260)
(242, 267)
(279, 297)
(292, 265)
(240, 270)
(264, 274)
(262, 260)
(253, 266)
(245, 281)
(242, 268)
(254, 257)
(289, 245)
(265, 256)
(274, 243)
(263, 311)
(236, 272)
(286, 268)
(250, 229)
(270, 271)
(245, 250)
(267, 253)
(235, 241)
(214, 221)
(250, 258)
(250, 276)
(272, 258)
(244, 262)
(256, 272)
(254, 253)
(274, 262)
(238, 269)
(251, 257)
(263, 241)
(252, 269)
(186, 252)
(198, 252)
(186, 232)
(210, 264)
(207, 255)
(254, 249)
(248, 280)
(213, 248)
(256, 255)
(271, 246)
(231, 269)
(271, 273)
(257, 264)
(242, 262)
(233, 279)
(221, 274)
(255, 254)
(230, 267)
(260, 302)
(259, 265)
(198, 252)
(186, 235)
(207, 276)
(177, 240)
(189, 252)
(177, 240)
(207, 232)
(219, 288)
(180, 240)
(189, 240)
(482, 760)
(156, 216)
(198, 252)
(180, 228)
(198, 252)
(207, 261)
(404, 514)
(207, 271)
(369, 646)
(195, 264)
(263, 290)
(258, 299)
(357, 514)
(198, 251)
(388, 618)
(382, 673)
(210, 276)
(272, 267)
(162, 216)
(150, 204)
(210, 276)
(189, 250)
(252, 243)
(474, 839)
(336, 565)
(180, 240)
(186, 252)
(198, 264)
(222, 246)
(207, 288)
(177, 228)
(227, 253)
(168, 227)
(195, 264)
(168, 252)
(198, 264)
(165, 216)
(195, 252)
(207, 263)
(210, 232)
(210, 276)
(171, 216)
(189, 240)
(207, 276)
(210, 280)
(265, 298)
(263, 321)
(156, 204)
(207, 254)
(168, 228)
(186, 240)
(198, 252)
(198, 252)
(189, 252)
(198, 243)
(180, 240)
(186, 240)
(189, 252)
(376, 668)
(177, 240)
(180, 228)
(210, 276)
(150, 166)
(210, 276)
(247, 242)
(174, 228)
(210, 276)
(189, 252)
(168, 228)
(198, 264)
(249, 247)
(207, 232)
(186, 252)
(177, 240)
(180, 240)
(180, 228)
(177, 240)
(186, 240)
(177, 240)
(210, 276)
(210, 273)
(186, 252)
(189, 252)
(195, 263)
(189, 252)
(198, 252)
(381, 603)
(180, 240)
(180, 228)
(150, 184)
(238, 269)
(186, 240)
(436, 778)
(372, 675)
(246, 257)
(244, 264)
(234, 273)
(310, 585)
(186, 237)
(150, 204)
(186, 252)
(180, 240)
(354, 604)
(171, 228)
(171, 228)
(198, 252)
(207, 276)
(189, 252)
(168, 228)
(189, 252)
(168, 228)
(236, 255)
(198, 264)
(189, 240)
(189, 244)
(373, 655)
(207, 276)
(210, 259)
(134, 204)
(186, 240)
(171, 228)
(219, 246)
(177, 240)
(186, 252)
(207, 276)
(189, 252)
(180, 240)
(207, 250)
(171, 228)
(198, 264)
(198, 240)
(180, 240)
(195, 264)
(195, 264)
(198, 264)
(164, 185)
(280, 276)
(266, 337)
(315, 257)
(303, 252)
(278, 264)
(289, 395)
(243, 248)
(278, 264)
(283, 361)
(244, 227)
(247, 223)
(245, 231)
(243, 266)
(303, 263)
(306, 293)
(258, 278)
(292, 268)
(240, 234)
(239, 260)
(269, 269)
(351, 281)
(269, 298)
(275, 274)
(251, 262)
(238, 250)
(240, 225)
(247, 271)
(283, 275)
(258, 257)
(234, 249)
(186, 240)
(207, 276)
(180, 240)
(177, 240)
(207, 257)
(186, 252)
(207, 269)
(198, 264)
(177, 240)
(177, 240)
(189, 252)
(180, 240)
(207, 264)
(180, 240)
(295, 374)
(186, 252)
(186, 252)
(150, 192)
(156, 216)
(189, 240)
(165, 216)
(177, 240)
(177, 240)
(189, 252)
(186, 252)
(210, 255)
(198, 276)
(177, 240)
(180, 221)
(198, 239)
(270, 261)
(198, 264)
(165, 216)
(180, 240)
(177, 228)
(198, 264)
(207, 276)
(207, 286)
(189, 252)
(198, 252)
(195, 252)
(222, 288)
(331, 578)
(241, 255)
(162, 216)
(195, 276)
(198, 264)
(180, 240)
(244, 240)
(189, 240)
(207, 254)
(301, 670)
(177, 240)
(317, 494)
(251, 238)
(150, 184)
(333, 654)
(186, 252)
(189, 252)
(177, 240)
(195, 264)
(198, 264)
(189, 252)
(186, 252)
(210, 264)
(177, 230)
(189, 252)
(390, 664)
(156, 216)
(189, 252)
(349, 452)
(186, 252)
(180, 227)
(242, 269)
(162, 204)
(189, 252)
(189, 242)
(198, 252)
(210, 276)
(239, 273)
(189, 252)
(189, 239)
(186, 247)
(195, 264)
(198, 264)
(189, 240)
(225, 239)
(245, 256)
(290, 583)
(180, 240)
(186, 252)
(189, 252)
(361, 649)
(186, 252)
(347, 584)
(207, 276)
(156, 204)
(139, 204)
(162, 216)
(189, 252)
(180, 240)
(210, 257)
(171, 228)
(156, 204)
(293, 469)
(189, 252)
(189, 246)
(177, 228)
(207, 276)
(156, 204)
(177, 240)
(186, 240)
(186, 252)
(243, 262)
(168, 228)
(180, 230)
(180, 228)
(252, 243)
(207, 276)
(189, 252)
(165, 216)
(186, 240)
(180, 236)
(150, 216)
(186, 252)
(198, 232)
(210, 259)
(207, 250)
(180, 228)
(232, 268)
(189, 252)
(189, 252)
(171, 228)
(210, 264)
(150, 166)
(186, 240)
(186, 241)
(132, 168)
(150, 192)
(248, 258)
(207, 276)
(186, 252)
(186, 252)
(247, 232)
(210, 266)
(162, 216)
(210, 266)
(210, 254)
(365, 553)
(186, 252)
(189, 252)
(189, 252)
(156, 204)
(198, 276)
(248, 275)
(189, 252)
(210, 276)
(381, 636)
(177, 229)
(198, 264)
(207, 276)
(180, 239)
(268, 312)
(186, 237)
(177, 240)
(207, 276)
(395, 664)
(198, 264)
(432, 663)
(177, 232)
(198, 263)
(132, 180)
(186, 252)
(260, 257)
(393, 613)
(207, 266)
(246, 259)
(168, 228)
(180, 240)
(186, 252)
(241, 264)
(384, 599)
(198, 245)
(207, 256)
(350, 587)
(210, 276)
(385, 609)
(347, 596)
(277, 257)
(186, 240)
(186, 252)
(162, 216)
(186, 252)
(177, 240)
(207, 266)
(180, 240)
(177, 240)
(258, 245)
(195, 264)
(198, 260)
(186, 252)
(189, 240)
(189, 252)
(402, 654)
(186, 240)
(198, 247)
(177, 240)
(261, 281)
(256, 283)
(120, 156)
(240, 239)
(207, 259)
(177, 240)
(198, 264)
(189, 237)
(346, 497)
(189, 241)
(171, 228)
(207, 232)
(207, 262)
(271, 266)
(272, 215)
(295, 318)
(216, 236)
(234, 278)
(247, 271)
(294, 257)
(241, 258)
(261, 227)
(262, 317)
(222, 281)
(255, 237)
(248, 238)
(314, 367)
(313, 316)
(295, 316)
(243, 235)
(296, 270)
(288, 278)
(287, 264)
(285, 405)
(292, 242)
(266, 238)
(270, 292)
(273, 242)
(283, 333)
(300, 287)
(311, 402)
(273, 248)
(285, 305)
(331, 328)
(306, 268)
(217, 228)
(295, 323)
(241, 300)
(281, 242)
(251, 322)
(254, 302)
(295, 227)
(280, 228)
(248, 244)
(324, 247)
(240, 351)
(236, 273)
(311, 292)
(256, 272)
(261, 276)
(357, 241)
(237, 236)
(291, 303)
(269, 257)
(349, 349)
(250, 249)
(281, 310)
(307, 428)
(240, 329)
(299, 310)
(248, 257)
(271, 233)
(285, 327)
(312, 263)
(258, 256)
(253, 301)
(277, 336)
(278, 308)
(216, 292)
(257, 272)
(273, 265)
(229, 240)
(266, 230)
(280, 301)
(240, 276)
(265, 258)
(276, 252)
(298, 212)
(237, 308)
(227, 304)
(233, 310)
(259, 286)
(332, 334)
(256, 324)
(249, 317)
(290, 357)
(312, 329)
(273, 369)
(303, 331)
(295, 337)
(248, 270)
(306, 321)
(232, 213)
(229, 306)
(270, 230)
(300, 237)
(294, 375)
(251, 330)
(301, 229)
(247, 314)
(233, 236)
(298, 310)
(258, 240)
(277, 287)
(248, 287)
(220, 207)
(269, 232)
(291, 319)
(269, 214)
(314, 278)
(297, 271)
(275, 293)
(267, 301)
(240, 332)
(280, 336)
(253, 309)
(256, 299)
(262, 327)
(247, 371)
(250, 300)
(253, 293)
(252, 386)
(245, 341)
(255, 312)
(271, 327)
(261, 308)
(232, 298)
(254, 209)
(250, 315)
(255, 320)
(249, 295)
(258, 358)
(259, 318)
(246, 368)
(240, 301)
(260, 309)
(234, 314)
(198, 264)
(189, 240)

In [23]:

count_size = Counter()
for item in train_dir.rglob("*"):
    if item.is_file():
        img = Image.open(item)
        count_size.update([img.size])
print("Size\t\t\tCount")
for size , count in sorted(count_size.items(), key=lambda x: x[1], reverse=True):
    # key=lambda x: x[1] یعنی بر اساس مولفه دوم مرتب کن
    # reverse = true  یعنی از بیشتر به کمتر سورت کن
    print(f"{size}\t\t{count}")

Size			Count
(198, 264)		67
(186, 252)		63
(189, 252)		58
(207, 276)		43
(198, 252)		37
(177, 240)		34
(180, 240)		33
(210, 276)		27
(171, 228)		25
(189, 240)		25
(162, 216)		24
(156, 204)		22
(195, 264)		21
(186, 240)		19
(180, 228)		18
(195, 252)		12
(165, 216)		11
(168, 228)		11
(171, 216)		10
(177, 228)		10
(150, 192)		10
(347, 448)		8
(198, 276)		7
(210, 264)		7
(207, 264)		6
(340, 448)		6
(156, 216)		5
(150, 189)		5
(349, 448)		5
(162, 204)		4
(207, 273)		4
(198, 247)		4
(186, 237)		4
(207, 254)		4
(135, 180)		4
(201, 264)		4
(331, 448)		4
(342, 448)		4
(198, 240)		4
(352, 448)		4
(207, 232)		4
(207, 259)		3
(210, 270)		3
(359, 448)		3
(198, 260)		3
(365, 448)		3
(356, 448)		3
(339, 448)		3
(392, 448)		3
(354, 448)		3
(315, 448)		3
(357, 448)		3
(348, 448)		3
(362, 448)		3
(354, 450)		3
(207, 261)		3
(210, 268)		3
(207, 257)		3
(284, 366)		3
(150, 204)		3
(186, 235)		2
(207, 274)		2
(129, 180)		2
(198, 239)		2
(207, 271)		2
(207, 262)		2
(177, 230)		2
(376, 450)		2
(344, 448)		2
(411, 448)		2
(343, 448)		2
(207, 268)		2
(390, 448)		2
(341, 448)		2
(366, 448)		2
(198, 254)		2
(144, 192)		2
(382, 448)		2
(350, 448)		2
(351, 448)		2
(367, 448)		2
(358, 448)		2
(334, 448)		2
(326, 448)		2
(338, 448)		2
(373, 448)		2
(207, 243)		2
(332, 448)		2
(320, 448)		2
(388, 448)		2
(372, 448)		2
(376, 448)		2
(337, 448)		2
(311, 433)		2
(210, 261)		2
(210, 257)		2
(346, 448)		2
(329, 448)		2
(345, 448)		2
(298, 267)		2
(268, 323)		2
(210, 254)		2
(210, 243)		2
(332, 334)		2
(198, 210)		2
(189, 235)		2
(198, 251)		2
(186, 232)		2
(378, 450)		2
(207, 288)		2
(138, 180)		2
(287, 349)		2
(297, 350)		2
(283, 366)		2
(251, 262)		2
(242, 262)		2
(256, 272)		2
(238, 269)		2
(252, 243)		2
(207, 263)		2
(210, 232)		2
(150, 166)		2
(150, 184)		2
(210, 259)		2
(207, 250)		2
(278, 264)		2
(247, 271)		2
(210, 255)		2
(210, 266)		2
(207, 266)		2
(227, 304)		2
(207, 275)		2
(307, 366)		1
(328, 365)		1
(253, 333)		1
(290, 326)		1
(286, 328)		1
(269, 397)		1
(272, 372)		1
(263, 341)		1
(263, 401)		1
(270, 355)		1
(269, 336)		1
(305, 353)		1
(290, 360)		1
(289, 339)		1
(248, 313)		1
(408, 495)		1
(268, 289)		1
(279, 366)		1
(237, 317)		1
(284, 339)		1
(222, 275)		1
(168, 216)		1
(210, 265)		1
(281, 326)		1
(462, 956)		1
(270, 361)		1
(198, 250)		1
(141, 180)		1
(189, 230)		1
(380, 787)		1
(425, 852)		1
(145, 216)		1
(256, 363)		1
(370, 553)		1
(117, 216)		1
(120, 168)		1
(177, 220)		1
(123, 168)		1
(201, 263)		1
(271, 333)		1
(171, 202)		1
(390, 870)		1
(189, 236)		1
(258, 356)		1
(249, 382)		1
(268, 300)		1
(321, 812)		1
(381, 440)		1
(361, 324)		1
(395, 440)		1
(374, 254)		1
(367, 349)		1
(434, 439)		1
(381, 387)		1
(337, 367)		1
(235, 260)		1
(378, 440)		1
(401, 381)		1
(266, 274)		1
(385, 440)		1
(415, 398)		1
(379, 341)		1
(380, 404)		1
(234, 225)		1
(666, 844)		1
(379, 352)		1
(376, 334)		1
(358, 426)		1
(441, 440)		1
(303, 293)		1
(326, 410)		1
(386, 418)		1
(386, 440)		1
(293, 418)		1
(288, 332)		1
(327, 330)		1
(241, 280)		1
(334, 450)		1
(323, 440)		1
(545, 590)		1
(356, 450)		1
(318, 393)		1
(331, 450)		1
(361, 450)		1
(341, 450)		1
(371, 437)		1
(328, 507)		1
(189, 248)		1
(369, 432)		1
(321, 448)		1
(353, 450)		1
(318, 450)		1
(349, 450)		1
(325, 450)		1
(321, 436)		1
(296, 359)		1
(395, 448)		1
(422, 448)		1
(370, 448)		1
(379, 448)		1
(345, 447)		1
(384, 443)		1
(320, 423)		1
(317, 406)		1
(344, 444)		1
(432, 448)		1
(433, 448)		1
(412, 448)		1
(403, 448)		1
(429, 448)		1
(222, 273)		1
(331, 444)		1
(332, 445)		1
(388, 442)		1
(406, 448)		1
(419, 448)		1
(329, 442)		1
(295, 366)		1
(431, 448)		1
(333, 448)		1
(336, 448)		1
(186, 236)		1
(389, 448)		1
(322, 443)		1
(311, 379)		1
(328, 448)		1
(306, 448)		1
(306, 406)		1
(369, 448)		1
(335, 448)		1
(393, 448)		1
(306, 414)		1
(402, 448)		1
(323, 448)		1
(337, 447)		1
(388, 440)		1
(319, 421)		1
(345, 445)		1
(368, 448)		1
(427, 448)		1
(334, 435)		1
(332, 440)		1
(364, 448)		1
(409, 415)		1
(322, 444)		1
(373, 410)		1
(325, 439)		1
(299, 411)		1
(185, 252)		1
(306, 404)		1
(324, 448)		1
(375, 448)		1
(163, 264)		1
(314, 414)		1
(329, 372)		1
(385, 448)		1
(207, 260)		1
(292, 364)		1
(284, 445)		1
(310, 432)		1
(413, 426)		1
(352, 440)		1
(420, 421)		1
(392, 440)		1
(369, 329)		1
(405, 392)		1
(350, 408)		1
(402, 373)		1
(325, 384)		1
(364, 440)		1
(306, 352)		1
(418, 440)		1
(306, 372)		1
(310, 351)		1
(329, 355)		1
(255, 249)		1
(348, 440)		1
(319, 413)		1
(256, 312)		1
(265, 301)		1
(337, 435)		1
(342, 379)		1
(325, 376)		1
(319, 342)		1
(315, 428)		1
(391, 336)		1
(322, 422)		1
(293, 306)		1
(302, 278)		1
(381, 450)		1
(361, 482)		1
(278, 267)		1
(379, 433)		1
(308, 419)		1
(195, 246)		1
(366, 419)		1
(352, 412)		1
(382, 416)		1
(351, 340)		1
(304, 417)		1
(219, 276)		1
(314, 419)		1
(189, 223)		1
(446, 448)		1
(326, 444)		1
(332, 425)		1
(317, 333)		1
(249, 216)		1
(128, 192)		1
(314, 413)		1
(278, 358)		1
(305, 403)		1
(330, 418)		1
(345, 355)		1
(338, 346)		1
(302, 376)		1
(341, 429)		1
(270, 253)		1
(315, 353)		1
(353, 390)		1
(312, 417)		1
(331, 355)		1
(323, 433)		1
(306, 425)		1
(378, 448)		1
(336, 411)		1
(298, 283)		1
(181, 260)		1
(298, 416)		1
(345, 375)		1
(319, 332)		1
(298, 362)		1
(335, 417)		1
(328, 417)		1
(302, 355)		1
(327, 396)		1
(366, 406)		1
(335, 404)		1
(345, 407)		1
(285, 341)		1
(342, 410)		1
(312, 448)		1
(351, 412)		1
(285, 320)		1
(290, 319)		1
(373, 438)		1
(361, 442)		1
(325, 446)		1
(432, 417)		1
(324, 433)		1
(313, 304)		1
(304, 318)		1
(384, 416)		1
(340, 408)		1
(373, 404)		1
(311, 369)		1
(198, 237)		1
(319, 346)		1
(336, 387)		1
(358, 359)		1
(321, 276)		1
(294, 405)		1
(304, 420)		1
(318, 409)		1
(357, 407)		1
(137, 252)		1
(153, 252)		1
(337, 405)		1
(350, 410)		1
(318, 400)		1
(332, 341)		1
(330, 357)		1
(317, 448)		1
(332, 388)		1
(292, 347)		1
(303, 376)		1
(299, 368)		1
(374, 448)		1
(297, 412)		1
(313, 369)		1
(338, 411)		1
(320, 351)		1
(336, 427)		1
(291, 418)		1
(362, 383)		1
(323, 442)		1
(310, 395)		1
(309, 324)		1
(286, 414)		1
(382, 392)		1
(331, 430)		1
(357, 408)		1
(403, 440)		1
(327, 448)		1
(348, 363)		1
(356, 413)		1
(163, 232)		1
(319, 416)		1
(313, 347)		1
(307, 372)		1
(333, 446)		1
(318, 401)		1
(315, 406)		1
(316, 407)		1
(303, 365)		1
(311, 335)		1
(298, 444)		1
(328, 426)		1
(316, 342)		1
(336, 423)		1
(317, 429)		1
(341, 409)		1
(266, 305)		1
(297, 369)		1
(349, 375)		1
(295, 418)		1
(329, 386)		1
(336, 415)		1
(356, 349)		1
(310, 352)		1
(256, 382)		1
(210, 272)		1
(250, 361)		1
(247, 340)		1
(265, 285)		1
(250, 331)		1
(383, 435)		1
(367, 384)		1
(350, 364)		1
(317, 370)		1
(347, 326)		1
(389, 393)		1
(314, 388)		1
(304, 340)		1
(306, 222)		1
(287, 290)		1
(303, 302)		1
(308, 319)		1
(371, 354)		1
(255, 252)		1
(287, 342)		1
(346, 302)		1
(249, 289)		1
(268, 396)		1
(267, 308)		1
(222, 201)		1
(326, 310)		1
(289, 367)		1
(450, 364)		1
(272, 342)		1
(253, 322)		1
(273, 419)		1
(296, 315)		1
(280, 290)		1
(337, 275)		1
(310, 378)		1
(312, 405)		1
(278, 346)		1
(251, 386)		1
(270, 415)		1
(284, 358)		1
(274, 333)		1
(164, 240)		1
(198, 244)		1
(281, 393)		1
(241, 297)		1
(290, 344)		1
(277, 392)		1
(303, 399)		1
(270, 386)		1
(277, 368)		1
(291, 358)		1
(276, 397)		1
(286, 387)		1
(299, 448)		1
(180, 229)		1
(269, 392)		1
(299, 446)		1
(274, 394)		1
(548, 754)		1
(271, 271)		1
(308, 350)		1
(302, 311)		1
(256, 239)		1
(276, 380)		1
(314, 380)		1
(293, 301)		1
(328, 395)		1
(313, 401)		1
(271, 376)		1
(358, 368)		1
(315, 377)		1
(286, 240)		1
(303, 377)		1
(331, 317)		1
(291, 329)		1
(313, 399)		1
(275, 354)		1
(278, 296)		1
(310, 448)		1
(272, 415)		1
(258, 366)		1
(291, 307)		1
(270, 290)		1
(316, 408)		1
(278, 381)		1
(276, 390)		1
(257, 333)		1
(286, 389)		1
(309, 416)		1
(283, 357)		1
(294, 370)		1
(275, 327)		1
(275, 391)		1
(238, 287)		1
(301, 410)		1
(285, 381)		1
(301, 366)		1
(306, 346)		1
(275, 369)		1
(295, 425)		1
(307, 322)		1
(313, 446)		1
(276, 321)		1
(320, 241)		1
(312, 342)		1
(291, 386)		1
(322, 416)		1
(264, 303)		1
(275, 384)		1
(306, 409)		1
(282, 387)		1
(287, 430)		1
(289, 327)		1
(353, 448)		1
(310, 405)		1
(325, 420)		1
(279, 316)		1
(273, 311)		1
(292, 373)		1
(180, 223)		1
(281, 388)		1
(289, 307)		1
(284, 385)		1
(281, 352)		1
(330, 368)		1
(195, 255)		1
(282, 375)		1
(261, 345)		1
(294, 411)		1
(305, 420)		1
(254, 232)		1
(293, 345)		1
(313, 398)		1
(291, 311)		1
(285, 367)		1
(271, 406)		1
(265, 318)		1
(301, 423)		1
(273, 287)		1
(277, 387)		1
(282, 347)		1
(292, 291)		1
(180, 252)		1
(281, 320)		1
(250, 281)		1
(275, 308)		1
(283, 370)		1
(283, 304)		1
(278, 357)		1
(285, 347)		1
(323, 444)		1
(354, 424)		1
(267, 241)		1
(267, 284)		1
(278, 370)		1
(320, 318)		1
(283, 254)		1
(255, 323)		1
(293, 369)		1
(277, 360)		1
(290, 293)		1
(269, 330)		1
(168, 232)		1
(293, 426)		1
(298, 448)		1
(294, 397)		1
(208, 332)		1
(183, 296)		1
(205, 280)		1
(211, 415)		1
(177, 310)		1
(170, 310)		1
(187, 320)		1
(325, 367)		1
(289, 301)		1
(331, 360)		1
(369, 364)		1
(312, 388)		1
(311, 408)		1
(281, 392)		1
(305, 400)		1
(290, 386)		1
(359, 399)		1
(294, 324)		1
(297, 326)		1
(250, 339)		1
(272, 376)		1
(294, 338)		1
(313, 333)		1
(337, 361)		1
(354, 333)		1
(273, 356)		1
(299, 360)		1
(285, 353)		1
(322, 367)		1
(321, 369)		1
(280, 381)		1
(287, 366)		1
(273, 368)		1
(303, 409)		1
(256, 373)		1
(251, 323)		1
(312, 339)		1
(293, 376)		1
(294, 399)		1
(356, 344)		1
(271, 373)		1
(317, 319)		1
(283, 309)		1
(305, 450)		1
(364, 450)		1
(375, 450)		1
(351, 450)		1
(366, 450)		1
(367, 442)		1
(397, 450)		1
(341, 383)		1
(394, 450)		1
(345, 440)		1
(393, 450)		1
(389, 450)		1
(361, 447)		1
(352, 450)		1
(380, 450)		1
(317, 450)		1
(343, 450)		1
(316, 450)		1
(280, 334)		1
(360, 442)		1
(387, 450)		1
(383, 450)		1
(382, 450)		1
(362, 439)		1
(282, 406)		1
(288, 391)		1
(300, 415)		1
(287, 395)		1
(134, 264)		1
(195, 243)		1
(298, 373)		1
(268, 353)		1
(306, 381)		1
(304, 366)		1
(210, 269)		1
(280, 365)		1
(310, 390)		1
(296, 370)		1
(265, 371)		1
(275, 360)		1
(287, 352)		1
(276, 354)		1
(287, 354)		1
(322, 401)		1
(290, 364)		1
(300, 356)		1
(288, 344)		1
(275, 368)		1
(207, 210)		1
(281, 373)		1
(277, 359)		1
(282, 439)		1
(287, 440)		1
(327, 365)		1
(299, 453)		1
(288, 353)		1
(268, 359)		1
(283, 347)		1
(291, 354)		1
(298, 358)		1
(274, 354)		1
(289, 353)		1
(287, 351)		1
(267, 358)		1
(299, 393)		1
(317, 325)		1
(302, 343)		1
(294, 359)		1
(282, 363)		1
(247, 345)		1
(291, 352)		1
(288, 351)		1
(292, 340)		1
(276, 358)		1
(288, 362)		1
(320, 395)		1
(290, 343)		1
(287, 347)		1
(301, 354)		1
(271, 377)		1
(276, 356)		1
(286, 354)		1
(290, 351)		1
(277, 358)		1
(293, 352)		1
(277, 370)		1
(284, 355)		1
(287, 365)		1
(280, 361)		1
(296, 348)		1
(304, 328)		1
(296, 354)		1
(297, 348)		1
(283, 350)		1
(280, 359)		1
(289, 357)		1
(295, 350)		1
(298, 348)		1
(284, 367)		1
(273, 363)		1
(299, 349)		1
(264, 348)		1
(300, 346)		1
(285, 375)		1
(298, 351)		1
(286, 401)		1
(315, 365)		1
(295, 357)		1
(288, 401)		1
(288, 361)		1
(293, 351)		1
(295, 348)		1
(288, 354)		1
(290, 388)		1
(291, 350)		1
(307, 406)		1
(282, 354)		1
(261, 350)		1
(299, 373)		1
(269, 361)		1
(286, 363)		1
(285, 360)		1
(292, 357)		1
(302, 397)		1
(288, 356)		1
(276, 361)		1
(295, 351)		1
(305, 368)		1
(286, 359)		1
(288, 367)		1
(208, 292)		1
(285, 361)		1
(198, 300)		1
(274, 265)		1
(281, 281)		1
(255, 250)		1
(216, 209)		1
(301, 293)		1
(303, 259)		1
(259, 252)		1
(319, 287)		1
(265, 218)		1
(288, 274)		1
(252, 296)		1
(269, 259)		1
(246, 273)		1
(251, 271)		1
(264, 210)		1
(278, 234)		1
(256, 298)		1
(281, 236)		1
(279, 290)		1
(236, 228)		1
(254, 252)		1
(246, 326)		1
(263, 257)		1
(231, 243)		1
(235, 222)		1
(245, 227)		1
(245, 272)		1
(255, 242)		1
(248, 251)		1
(222, 260)		1
(247, 296)		1
(259, 257)		1
(324, 279)		1
(278, 272)		1
(240, 264)		1
(253, 296)		1
(271, 264)		1
(292, 262)		1
(222, 245)		1
(273, 271)		1
(264, 238)		1
(241, 274)		1
(234, 257)		1
(235, 261)		1
(262, 251)		1
(232, 260)		1
(222, 219)		1
(253, 260)		1
(242, 267)		1
(279, 297)		1
(292, 265)		1
(240, 270)		1
(264, 274)		1
(262, 260)		1
(253, 266)		1
(245, 281)		1
(242, 268)		1
(254, 257)		1
(289, 245)		1
(265, 256)		1
(274, 243)		1
(263, 311)		1
(236, 272)		1
(286, 268)		1
(250, 229)		1
(270, 271)		1
(245, 250)		1
(267, 253)		1
(235, 241)		1
(214, 221)		1
(250, 258)		1
(250, 276)		1
(272, 258)		1
(244, 262)		1
(254, 253)		1
(274, 262)		1
(251, 257)		1
(263, 241)		1
(252, 269)		1
(207, 255)		1
(254, 249)		1
(248, 280)		1
(213, 248)		1
(256, 255)		1
(271, 246)		1
(231, 269)		1
(271, 273)		1
(257, 264)		1
(233, 279)		1
(221, 274)		1
(255, 254)		1
(230, 267)		1
(260, 302)		1
(259, 265)		1
(219, 288)		1
(482, 760)		1
(404, 514)		1
(369, 646)		1
(263, 290)		1
(258, 299)		1
(357, 514)		1
(388, 618)		1
(382, 673)		1
(272, 267)		1
(189, 250)		1
(474, 839)		1
(336, 565)		1
(222, 246)		1
(227, 253)		1
(168, 227)		1
(168, 252)		1
(210, 280)		1
(265, 298)		1
(263, 321)		1
(198, 243)		1
(376, 668)		1
(247, 242)		1
(174, 228)		1
(249, 247)		1
(210, 273)		1
(195, 263)		1
(381, 603)		1
(436, 778)		1
(372, 675)		1
(246, 257)		1
(244, 264)		1
(234, 273)		1
(310, 585)		1
(354, 604)		1
(236, 255)		1
(189, 244)		1
(373, 655)		1
(134, 204)		1
(219, 246)		1
(164, 185)		1
(280, 276)		1
(266, 337)		1
(315, 257)		1
(303, 252)		1
(289, 395)		1
(243, 248)		1
(283, 361)		1
(244, 227)		1
(247, 223)		1
(245, 231)		1
(243, 266)		1
(303, 263)		1
(306, 293)		1
(258, 278)		1
(292, 268)		1
(240, 234)		1
(239, 260)		1
(269, 269)		1
(351, 281)		1
(269, 298)		1
(275, 274)		1
(238, 250)		1
(240, 225)		1
(283, 275)		1
(258, 257)		1
(234, 249)		1
(207, 269)		1
(295, 374)		1
(180, 221)		1
(270, 261)		1
(207, 286)		1
(222, 288)		1
(331, 578)		1
(241, 255)		1
(195, 276)		1
(244, 240)		1
(301, 670)		1
(317, 494)		1
(251, 238)		1
(333, 654)		1
(390, 664)		1
(349, 452)		1
(180, 227)		1
(242, 269)		1
(189, 242)		1
(239, 273)		1
(189, 239)		1
(186, 247)		1
(225, 239)		1
(245, 256)		1
(290, 583)		1
(361, 649)		1
(347, 584)		1
(139, 204)		1
(293, 469)		1
(189, 246)		1
(243, 262)		1
(180, 230)		1
(180, 236)		1
(150, 216)		1
(198, 232)		1
(232, 268)		1
(186, 241)		1
(132, 168)		1
(248, 258)		1
(247, 232)		1
(365, 553)		1
(248, 275)		1
(381, 636)		1
(177, 229)		1
(180, 239)		1
(268, 312)		1
(395, 664)		1
(432, 663)		1
(177, 232)		1
(198, 263)		1
(132, 180)		1
(260, 257)		1
(393, 613)		1
(246, 259)		1
(241, 264)		1
(384, 599)		1
(198, 245)		1
(207, 256)		1
(350, 587)		1
(385, 609)		1
(347, 596)		1
(277, 257)		1
(258, 245)		1
(402, 654)		1
(261, 281)		1
(256, 283)		1
(120, 156)		1
(240, 239)		1
(189, 237)		1
(346, 497)		1
(189, 241)		1
(271, 266)		1
(272, 215)		1
(295, 318)		1
(216, 236)		1
(234, 278)		1
(294, 257)		1
(241, 258)		1
(261, 227)		1
(262, 317)		1
(222, 281)		1
(255, 237)		1
(248, 238)		1
(314, 367)		1
(313, 316)		1
(295, 316)		1
(243, 235)		1
(296, 270)		1
(288, 278)		1
(287, 264)		1
(285, 405)		1
(292, 242)		1
(266, 238)		1
(270, 292)		1
(273, 242)		1
(283, 333)		1
(300, 287)		1
(311, 402)		1
(273, 248)		1
(285, 305)		1
(331, 328)		1
(306, 268)		1
(217, 228)		1
(295, 323)		1
(241, 300)		1
(281, 242)		1
(251, 322)		1
(254, 302)		1
(295, 227)		1
(280, 228)		1
(248, 244)		1
(324, 247)		1
(240, 351)		1
(236, 273)		1
(311, 292)		1
(261, 276)		1
(357, 241)		1
(237, 236)		1
(291, 303)		1
(269, 257)		1
(349, 349)		1
(250, 249)		1
(281, 310)		1
(307, 428)		1
(240, 329)		1
(299, 310)		1
(248, 257)		1
(271, 233)		1
(285, 327)		1
(312, 263)		1
(258, 256)		1
(253, 301)		1
(277, 336)		1
(278, 308)		1
(216, 292)		1
(257, 272)		1
(273, 265)		1
(229, 240)		1
(266, 230)		1
(280, 301)		1
(240, 276)		1
(265, 258)		1
(276, 252)		1
(298, 212)		1
(237, 308)		1
(233, 310)		1
(259, 286)		1
(256, 324)		1
(249, 317)		1
(290, 357)		1
(312, 329)		1
(273, 369)		1
(303, 331)		1
(295, 337)		1
(248, 270)		1
(306, 321)		1
(232, 213)		1
(229, 306)		1
(270, 230)		1
(300, 237)		1
(294, 375)		1
(251, 330)		1
(301, 229)		1
(247, 314)		1
(233, 236)		1
(298, 310)		1
(258, 240)		1
(277, 287)		1
(248, 287)		1
(220, 207)		1
(269, 232)		1
(291, 319)		1
(269, 214)		1
(314, 278)		1
(297, 271)		1
(275, 293)		1
(267, 301)		1
(240, 332)		1
(280, 336)		1
(253, 309)		1
(256, 299)		1
(262, 327)		1
(247, 371)		1
(250, 300)		1
(253, 293)		1
(252, 386)		1
(245, 341)		1
(255, 312)		1
(271, 327)		1
(261, 308)		1
(232, 298)		1
(254, 209)		1
(250, 315)		1
(255, 320)		1
(249, 295)		1
(258, 358)		1
(259, 318)		1
(246, 368)		1
(240, 301)		1
(260, 309)		1
(234, 314)		1
(235, 314)		1
(198, 269)		1
(274, 272)		1
(237, 268)		1
(201, 252)		1
(289, 640)		1
(171, 213)		1
(189, 247)		1
(253, 366)		1
(251, 295)		1
(186, 234)		1
(255, 286)		1
(288, 404)		1
(207, 267)		1
(281, 323)		1
(207, 272)		1
(452, 926)		1
(267, 321)		1
(139, 216)		1
(239, 334)		1
(272, 317)		1
(247, 374)		1
(253, 312)		1
(198, 257)		1
(263, 309)		1
(186, 251)		1
(189, 238)		1
(132, 237)		1
(129, 216)		1

In [ ]:
import matplotlib.pylab as plt
# for image in ImageFolder:
#     print(image) 

fig , axes = plt.subplots(8,5 , figsize = (20,25))
axes = axes.ravel()

class_count = [0] * 8

for label in range(8):

    for image , image_label in train_dataset:
        if(image_label == label):
                position = label *5 + count_img
                axes[position].imshow(image)
                axes[position].set_title(train_dataset.classes[label])

                count_img += 1
                if (count_img >= 5):
                     break

plt.show()

In [19]:
# import matplotlib.pyplot as plt
# from PIL import Image

# # فقط ۲۰ تصویر اول را نمایش بده
# fig, axes = plt.subplots(4, 5, figsize=(15, 12))
# axes = axes.ravel()

# for i in range(20):
#     image, label = train_dataset[i]
#     axes[i].imshow(image)
#     axes[i].set_title(train_dataset.classes[label])
#     axes[i].axis("off")

# plt.tight_layout()
# plt.show()
# plt.close(fig)  # ← این خط خیلی مهم است

In [25]:
print("Number of classes:", len(train_dataset.classes))
print("Classes:", train_dataset.classes)
print("Dataset size:", len(train_dataset))

Number of classes: 8
Classes: ['ambulance', 'autobus', 'kamyun', 'kamyunet', 'minibus', 'savari', 'taxi', 'vanet']
Dataset size: 1932

In [26]:
import torch
import matplotlib.pyplot as plt
from PIL import Image

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Matplotlib and PIL imported successfully")

PyTorch: 2.14.0+cpu
CUDA available: False
Matplotlib and PIL imported successfully

In [27]:
from hashlib import md5

for p in train_dir.rglob("*"):
    if p.is_file():
        with open(p, "rb") as f:
            image_bytes = f.read()

image_hash = md5(image_bytes).hexdigest()

print("Image:", p)
print("Hash:", image_hash)
# print(image_bytes)

Image: C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\vanet\219127494.jpg
Hash: 384eb2ac7439cd3363cec845d10f6eb0

In [28]:
from hashlib import md5

hashes = {}
for image_path in train_dir.rglob("*"):
    if image_path.is_file():
        with open(image_path,"rb") as f:
            images_bytes = f.read()
        images_hash  = md5(images_bytes).hexdigest()
        hashes[image_path] = images_hash
print(len(hashes))

1932

In [29]:
for image_path, image_hash in list(hashes.items())[:5]:
    print(image_path)
    print(image_hash)
    print()

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\195939523.jpg
729acf5fc1034ec77741e16b50fc95b0

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\198727855.jpg
5ba6cc623db387180f5fe1520e3ad38e

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199031396.jpg
5e066ebda81ef9f19d1d849befbbb0d2

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199587392.jpg
bcec609801e88317e8a6ae65125a99e4

C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge\ambulance\199659807.jpg
56a4a2003e35cd2cc59048594222c45e

In [30]:
hash_count = Counter(hashes.values())
print(hash_count.most_common(10))

[('729acf5fc1034ec77741e16b50fc95b0', 1), ('5ba6cc623db387180f5fe1520e3ad38e', 1), ('5e066ebda81ef9f19d1d849befbbb0d2', 1), ('bcec609801e88317e8a6ae65125a99e4', 1), ('56a4a2003e35cd2cc59048594222c45e', 1), ('c8b7572f399aa7e3ad2cc8e864b40abf', 1), ('412b8d98abb98eba00be5f85c0f85db9', 1), ('adec8de0ff32591cccf1b902da333249', 1), ('1c8e09b838ab8fe822eae04dc93c95af', 1), ('73e81bfd4d526729f05a201fcf5fe923', 1)]

In [31]:
duplicates_hash = {
    image_hash: count
    for image_hash,count in hash_count.items()
    if count>1
}
print(duplicates_hash)

{}

بررسی تصاویر مشکوک و دارای لیبل نامرتبط

In [ ]:
import matplotlib.pylab as plt
# for image in ImageFolder:
#     print(image) 

fig , axes = plt.subplots(8,10 , figsize = (20,25))
axes = axes.ravel()

for label in range(8):
    count_img = 0
    for image , image_label in train_dataset:
        if(image_label == label):
                position = label *10 + count_img
                axes[position].imshow(image)
                axes[position].set_title(train_dataset.classes[label])

                count_img += 1
                if (count_img >= 10):
                     break

plt.show()

In [ ]:
import matplotlib.pyplot as plt

images = []

for image, image_label in train_dataset:
    images.append((image, image_label))

for start in range(0, len(images), 20):

    fig, axes = plt.subplots(4, 5, figsize=(15, 12))
    axes = axes.ravel()

    batch = images[start:start + 20]

    for i, (image, image_label) in enumerate(batch):

        axes[i].imshow(image)
        axes[i].set_title(train_dataset.classes[image_label])
        axes[i].axis("off")

    plt.tight_layout()
    plt.show()

In [34]:
class_name = ["ambulance","kamyunet","savari","vanet","taxi", "autobus", "kamyun","minibus"]

In [35]:
suspicious = {
    "ambulance":[201107960,217579095],

    "taxi" : [217255043,218136743,218147453,218268791,218655409,216191824
              ,218501211],

    "autobus" : [216664450,216802875],

    "kamyun" : [214831926,215888901,215989939,216040476,216847004,218935445
                ,218936367,198119425,201179873,199172201,206174596,210109298
                ,210749256,214657348,215099946,216822835,215635130,215692883
                ,215721968,216008162,216010811,216039996,216048837,216026504
                ,216801664,216158404,216133020,216293604,216561920,216710667
                ,216977256,217007653,216835885,216984093,217067503,217219987
                ,217341470,217957818,218154755,218231967,218532550,218719693
                ,218720188,218827750,218906168,218967036,219002808,219057756
                ,219095831],

    "minibus" : [198885269,205763607,199981262,216127047,216428820,216999560
                 ,217197302,218573670,218588746,217712958,218145869,218728399
                 ,218740264],

    "vanet": [216830335],
    
    "savari": [203730891,206803325]

}

In [36]:
from pathlib import Path
import pandas as pd

root = Path(train_dataset.root)
# نگه داشتن مسیر اصلی دیتاست همان دیتای ترکیب  شده

all_files = {
    path.stem: path
    # نام فایل بدون پسوند jpg
    for path in root.rglob("*")
    # تمام فایل ها از جمله پوشه ها و زیرپوشه های فایل اصلی (ریشه) را پیداکن
    if path.is_file() and path.suffix.lower() in [".jpg", ".jpeg", ".png"]
}

found = []
not_found = []

for class_name, image_ids in suspicious.items():

    for image_id in image_ids:

        image_id = str(image_id)

        if image_id in all_files:
            path = all_files[image_id]

            found.append({
                "filename": path.name,
                "current_label": path.parent.name,
                "expected_label": class_name,
                "path": str(path)
            })

        else:
            not_found.append((class_name, image_id))

print("Found:", len(found))
print("Not found:", len(not_found))

Found: 76
Not found: 0

In [37]:
suspicious_df = pd.DataFrame(found)

display(suspicious_df.head(10))

,filename,current_label,expected_label,path
0,201107960.jpg,ambulance,ambulance,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
1,217579095.jpg,ambulance,ambulance,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
2,217255043.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
3,218136743.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
4,218147453.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
5,218268791.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
6,218655409.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
7,216191824.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
8,218501211.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
9,216664450.jpg,autobus,autobus,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...

In [ ]:
import math

n = len(found)

cols = 8
rows = math.ceil(n / cols)

fig, axes = plt.subplots(
    rows,
    cols,
    figsize=(24, rows * 3)
)

axes = axes.flatten()

for ax, item in zip(axes, found):

    img = Image.open(item["path"])

    ax.imshow(img)

    ax.set_title(
        f'{item["filename"]}\n'
        f'{item["current_label"]}',
        fontsize=12
    )

    ax.axis("off")

for ax in axes[len(found):]:
    ax.axis("off")

plt.tight_layout()
plt.show()

In [39]:
new_decisions = {
    "201107960": ("ambiguous", None, "wrong_vehicle_type"),
    # "209441415": ("ambiguous", None, "wrong_vehicle_type"),
    # "211996658": ("ambiguous", None, "wrong_vehicle_type"),
    "217579095": ("ambiguous", None, "wrong_vehicle_type"),
    # "217526919": ("ambiguous", None, "wrong_vehicle_type"),


    # "216860191": ("unrelated", None, "wrong_vehicle_type"),
    "217255043": ("unrelated", None, "wrong_vehicle_type"),
    "218136743": ("keep", None, "low_resolution"),
    "218147453": ("unrelated", None, "wrong_vehicle_type"),
    "218268791": ("unrelated", None, "wrong_vehicle_type"),
    "218655409": ("keep", None, "low_resolution"),
    "216191824": ("unrelated", None, "wrong_vehicle_type"),
    "218501211": ("unrelated", None, "wrong_vehicle_type"),

    # "214619456": ("keep", None, "correct_image"),
    "216664450": ("near_duplicate", None, "similar_image"),
    "216802875": ("keep", None, "similar_image"),

    "214831926": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "215888901": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "215989939": ("wrong_label", "kamyunet", "wrong_vehicle_type"),    
    "216040476": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216847004": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218935445": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218936367": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "198119425": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "201179873": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "199172201": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "206174596": ("wrong_label", "kamyunet", "wrong_vehicle_type"),    
    "210109298": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "210749256": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "214657348": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "215099946": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216822835": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "215635130": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "215692883": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "215721968": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216008162": ("wrong_label", "kamyunet", "wrong_vehicle_type"),    
    "216010811": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216039996": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216048837": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216026504": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216801664": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216158404": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216133020": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216293604": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216561920": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216710667": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216977256": ("wrong_label", "kamyunet", "wrong_vehicle_type"),    
    "217007653": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216835885": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "216984093": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "217067503": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "217219987": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "217341470": ("wrong_label", "kamyunet", "wrong_vehicle_type"),    
    "217957818": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218154755": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218231967": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218532550": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218719693": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218720188": ("wrong_label", "kamyunet", "wrong_vehicle_type"),    
    "218827750": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218906168": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "218967036": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "219002808": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "219057756": ("wrong_label", "kamyunet", "wrong_vehicle_type"),
    "219095831": ("wrong_label", "kamyunet", "wrong_vehicle_type"),

    "198885269":("wrong_label", "autobus", "wrong_vehicle_type"),
    "205763607":("ambiguous",None,"corrupted"),
    "199981262":("wrong_label", "autobus", "wrong_vehicle_type"),
    "216127047":("wrong_label", "autobus", "wrong_vehicle_type"),
    "216428820":("wrong_label", "autobus", "wrong_vehicle_type"),
    "216999560":("near_duplicate", None, "similar_image"),
    "217197302":("near_duplicate", None, "similar_image"),
    "218573670":("near_duplicate", None, "similar_image"),
    "218588746":("keep", None, "similar_image"),
    "217712958":("ambiguous",None,"low_resolution"),
    "218145869":("keep",None,"low_resolution"),
    "218728399":("near_duplicate", None, "similar_image"),
    "218740264":("keep", None, "similar_image"),



    "216830335" : ("ambiguous", None, "unclear_class"),


    "203730891": ("wrong_label", "taxi", "wrong_vehicle_type"),
    "206803325": ("wrong_label", "taxi", "wrong_vehicle_type")
}

In [40]:
df = pd.DataFrame.from_dict(
    new_decisions,
    orient="index",
    columns=["decision", "target_label", "reason"]
)

df.index.name = "image_id"

df.head()

            decision target_label              reason
image_id
201107960  ambiguous          NaN  wrong_vehicle_type
217579095  ambiguous          NaN  wrong_vehicle_type
217255043  unrelated          NaN  wrong_vehicle_type
218136743       keep          NaN      low_resolution
218147453  unrelated          NaN  wrong_vehicle_type

In [41]:
audit_df = pd.DataFrame(found)

audit_df["image_id"] = (
    audit_df["filename"].str.replace(".jpg", "", regex=False)
)

decisions_df = pd.DataFrame.from_dict(
    new_decisions,
    orient="index",
    columns=["decision", "target_label", "reason"]
)

decisions_df.index.name = "image_id"

audit_df = audit_df.merge(
    decisions_df,
    on="image_id",
    how="left"
)

audit_df.head()

,filename,current_label,expected_label,path,image_id,decision,target_label,reason
0,201107960.jpg,ambulance,ambulance,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,201107960,ambiguous,NaN,wrong_vehicle_type
1,217579095.jpg,ambulance,ambulance,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,217579095,ambiguous,NaN,wrong_vehicle_type
2,217255043.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,217255043,unrelated,NaN,wrong_vehicle_type
3,218136743.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,218136743,keep,NaN,low_resolution
4,218147453.jpg,taxi,taxi,C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,218147453,unrelated,NaN,wrong_vehicle_type

In [42]:
count_decision = Counter()
for decision in new_decisions.values():
    count_decision[decision[0]] +=1
print("decision : ", count_decision)

decision :  Counter({'wrong_label': 55, 'keep': 6, 'ambiguous': 5, 'unrelated': 5, 'near_duplicate': 5})

In [43]:

merge_dir = Path(r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean")

class_counts = Counter()

for class_dir in merge_dir.iterdir():
    if class_dir.is_dir():
        count = sum(1 for p in class_dir.iterdir() if p.is_file())
        class_counts[class_dir.name] = count

for class_name, count in class_counts.items():
    print(class_name, ":", count)

ambulance : 217
autobus : 249
kamyun : 201
kamyunet : 287
minibus : 224
savari : 248
taxi : 247
vanet : 249

بررسی تصاویر مشابه به کمک pHash

In [56]:
autobus_dir = data_dir / "train - merge - clean" / "autobus"

print("Path exists:", autobus_dir.exists())
print("Resolved path:", autobus_dir.resolve())

Path exists: True
Resolved path: C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\autobus

In [57]:
image_paths = [
    path for path in autobus_dir.iterdir()
    if path.is_file()
]

print("Number of images:", len(image_paths))

Number of images: 249

In [58]:
hashes = {}

for path in image_paths:
    try:
        with Image.open(path) as img:
            hashes[path] = imagehash.phash(img)

    except Exception as e:
        print("Error:", path.name, e)

print("Number of hashes:", len(hashes))

Number of hashes: 249

In [62]:
from itertools import combinations

In [63]:
similar_pairs = []

for (path1, hash1), (path2, hash2) in combinations(hashes.items(), 2):
    distance = hash1 - hash2

    if distance <= 10:
        similar_pairs.append({
            "image_1": path1.name,
            "image_2": path2.name,
            "distance": distance,
            "path_1": str(path1),
            "path_2": str(path2)
        })

similar_df = pd.DataFrame(similar_pairs)

similar_df = similar_df.sort_values(
    "distance"
).reset_index(drop=True)

print("Similar pairs:", len(similar_df))

similar_df.head(20)

Similar pairs: 145

,image_1,image_2,distance,path_1,path_2
0,216079914.jpg,217431762.jpg,2,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
1,216859234.jpg,218028985.jpg,4,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
2,216551896.jpg,217780130.jpg,4,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
3,217091265.jpg,218625583.jpg,4,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
4,218092463.jpg,218952897.jpg,4,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
5,218028985.jpg,218060991.jpg,4,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
6,213748478.jpg,214187028.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
7,213748478.jpg,216079914.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
8,216079914.jpg,218959354.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
9,216240222.jpg,218903278.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
10,216946113.jpg,218932432.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
11,216277099.jpg,218028985.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
12,215992943.jpg,217091265.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
13,216066402.jpg,218625583.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
14,216066402.jpg,217091265.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
15,216010502.jpg,216412255.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
16,217431762.jpg,218959354.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
17,217091265.jpg,217893775.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
18,217893775.jpg,218625583.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
19,218060991.jpg,218767971.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...

In [ ]:
import matplotlib.pyplot as plt
from PIL import Image

top_pairs = similar_df[similar_df["distance"] <= 4]

for _, row in top_pairs.iterrows():

    img1 = Image.open(row["path_1"])
    img2 = Image.open(row["path_2"])

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(img1)
    axes[0].set_title(row["image_1"])

    axes[1].imshow(img2)
    axes[1].set_title(row["image_2"])

    axes[0].axis("off")
    axes[1].axis("off")

    plt.suptitle(f"Hamming Distance: {row['distance']}")
    plt.tight_layout()
    plt.show()

In [83]:
taxi_dir = data_dir / "train - merge - clean" / "taxi"

print("Path exists:", autobus_dir.exists())
print("Resolved path:", autobus_dir.resolve())
image_paths = [
    path for path in taxi_dir.iterdir()
    if path.is_file()
]

print("Number of images:", len(image_paths))
hashes = {}

for path in image_paths:
    try:
        with Image.open(path) as img:
            hashes[path] = imagehash.phash(img)

    except Exception as e:
        print("Error:", path.name, e)

print("Number of hashes:", len(hashes))
similar_pairs = []

for (path1, hash1), (path2, hash2) in combinations(hashes.items(), 2):
    distance = hash1 - hash2

    if distance <= 10:
        similar_pairs.append({
            "image_1": path1.name,
            "image_2": path2.name,
            "distance": distance,
            "path_1": str(path1),
            "path_2": str(path2)
        })

similar_df = pd.DataFrame(similar_pairs)

similar_df = similar_df.sort_values(
    "distance"
).reset_index(drop=True)

print("Similar pairs:", len(similar_df))

similar_df.head(20)

Path exists: True
Resolved path: C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\taxi
Number of images: 247
Number of hashes: 247
Similar pairs: 54

,image_1,image_2,distance,path_1,path_2
0,218377804.jpg,218787302.jpg,4,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
1,199044255.jpg,200326261.jpg,6,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
2,212737728.jpg,216893661.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
3,203730891.jpg,206803325.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
4,215773124.jpg,217426237.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
5,215773124.jpg,218690372.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
6,214698644.jpg,217426237.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
7,212237527.jpg,216893661.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
8,216968614.jpg,218690372.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
9,218045822.jpg,218402981.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
10,218321884.jpg,218787302.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
11,218104747.jpg,218320753.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
12,216210740.jpg,217405463.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
13,217601310.jpg,218320753.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
14,215920981.jpg,216373693.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
15,214833819.jpg,215773124.jpg,8,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
16,214678598.jpg,215086606.jpg,10,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
17,214628757.jpg,216118231.jpg,10,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
18,213061361.jpg,218738200.jpg,10,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...
19,211997826.jpg,216893661.jpg,10,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...,c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه...

In [ ]:
import matplotlib.pyplot as plt
from PIL import Image

top_pairs = similar_df[similar_df["distance"] <= 4]

for _, row in top_pairs.iterrows():

    img1 = Image.open(row["path_1"])
    img2 = Image.open(row["path_2"])

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(img1)
    axes[0].set_title(row["image_1"])

    axes[1].imshow(img2)
    axes[1].set_title(row["image_2"])

    axes[0].axis("off")
    axes[1].axis("off")

    plt.suptitle(f"Hamming Distance: {row['distance']}")
    plt.tight_layout()
    plt.show()

In [65]:
from pathlib import Path
from PIL import Image
import imagehash

target_numbers_autobus = ["216664450", "216802875"]
project_dir = Path.cwd().parent

autobus_dir = project_dir / "data" / "train - merge - clean" / "autobus"

for path in autobus_dir.iterdir():
    if path.is_file():
        filename = path.stem

        if any(number in filename for number in target_numbers_autobus):
            print(filename, path)

216664450 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\autobus\216664450.jpg
216802875 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\autobus\216802875.jpg

In [77]:
path_216664450 = r"c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\autobus\216664450.jpg"
path_216802875 = r"c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\autobus\216802875.jpg"

image_216664450 = Image.open(path_216664450)
image_216802875 = Image.open(path_216802875)

hash_216664450 =imagehash.phash(image_216664450)
hash_216802875 =imagehash.phash(image_216802875)

print("Hash 216664450 :",hash_216664450)
print("Hash 216802875 :",hash_216802875)

distance = hash_216664450 - hash_216802875
print("hamming distance : ",distance)

Hash 216664450 : bd179928db19a991
Hash 216802875 : 951bd999d959a852
hamming distance :  16

In [73]:
target_numbers_minibus1 = ["217197302", "218573670","218588746","216999560"]

target_numbers_minibus1 = [
    "217197302",
    "218573670",
    "218588746",
    "216999560"
]

project_dir = Path.cwd().parent

minibus_dir = project_dir / "data" / "train - merge - clean" / "minibus"

found_numbers = []

for path in minibus_dir.iterdir():
    if path.is_file():
        filename = path.stem

        if filename in target_numbers_minibus1:
            found_numbers.append(filename)
            print(filename, path)

print("Found:", len(found_numbers))
print("Not found:", set(target_numbers_minibus1) - set(found_numbers))

216999560 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\216999560.jpg
217197302 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\217197302.jpg
218573670 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\218573670.jpg
218588746 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\218588746.jpg
Found: 4
Not found: set()

In [74]:
path_216999560 = r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train\autobus\216664450.jpg"
path_217197302 = r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train\autobus\216802875.jpg"
path_218573670 = r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train\autobus\216664450.jpg"
path_218588746 = r"C:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train\autobus\216802875.jpg"

image_216999560 = Image.open(path_216999560)
image_217197302 = Image.open(path_217197302)
image_218573670 = Image.open(path_218573670)
image_218588746 = Image.open(path_218588746)

hash_216999560 =imagehash.phash(image_216999560)
hash_217197302 =imagehash.phash(image_217197302)
hash_218573670 =imagehash.phash(image_218573670)
hash_218588746 =imagehash.phash(image_218588746)

print("Hash 216999560 :",hash_216999560)
print("Hash 217197302 :",hash_217197302)
print("Hash 218573670 :",hash_218573670)
print("Hash 218588746 :",hash_218588746)

Hash 216999560 : bd179928db19a991
Hash 217197302 : 951bd999d959a852
Hash 218573670 : bd179928db19a991
Hash 218588746 : 951bd999d959a852

In [79]:
hashes = {
    "216999560": hash_216999560,
    "217197302": hash_217197302,
    "218573670": hash_218573670,
    "218588746": hash_218588746
}


# محاسبه فاصله همینگ بین تمام جفت تصاویر
distance_results = []

for (name1, hash1), (name2, hash2) in combinations(hashes.items(), 2):

    distance = hash1 - hash2

    distance_results.append({
        "image_1": name1,
        "image_2": name2,
        "hamming_distance": distance
    })


# نمایش نتایج
distance_df = pd.DataFrame(distance_results)

distance_df = distance_df.sort_values(
    "hamming_distance"
).reset_index(drop=True)

distance_df

     image_1    image_2  hamming_distance
0  216999560  218573670                 0
1  217197302  218588746                 0
2  216999560  218588746                16
3  216999560  217197302                16
4  217197302  218573670                16
5  218573670  218588746                16

In [76]:
target_numbers_minibus2 = ["218728399", "218740264"]

project_dir = Path.cwd().parent

minibus_dir = project_dir / "data" / "train - merge - clean" / "minibus"

found_numbers = []

for path in minibus_dir.iterdir():
    if path.is_file():
        filename = path.stem

        if filename in target_numbers_minibus2:
            found_numbers.append(filename)
            print(filename, path)

print("Found:", len(found_numbers))
print("Not found:", set(target_numbers_minibus2) - set(found_numbers))

218728399 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\218728399.jpg
218740264 c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\218740264.jpg
Found: 2
Not found: set()

In [80]:
path_218728399 = r"c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\218728399.jpg"
path_218740264 = r"c:\Users\ASUS\Desktop\مکتب شریف\مکتب 145\پروژه دوم\data\train - merge - clean\minibus\218740264.jpg"

image_218728399 = Image.open(path_218728399)
image_218740264 = Image.open(path_218740264)

hash_218728399 =imagehash.phash(image_218728399)
hash_218740264 =imagehash.phash(image_218740264)

print("Hash 218728399 :",hash_218728399)
print("Hash 218740264 :",hash_218740264)

distance = hash_218728399 - hash_218740264
print("hamming distance : ",distance)

Hash 218728399 : dad42de860c3c72d
Hash 218740264 : c2ad297438967579
hamming distance :  26

با توجه به شباهت زیاد این دو تصویر و یکسان بودن پلاک خودروها تصمیم گرفتیم به کمک pHash
شباهت آنهارا بسنجیم که در نهایت مشاهده کردیم فاصله همینگ آنها عددی برابر 14 دارد که نشان دهنده این است که تنها
14 بیت متفاوت دارندو این عدد کمی است
در نیتجه تصمیمی که در مورد آنها گرفتم تا حد زیادی درست است